### ISSUE TITLE
CDATA

### ISSUE THREAD

**Issue by marlboro** [kawanet/to-xml#3]
Nice module, but it doesn't seem to support CDATA correctly as it's always encoding it when it should leave it alone.

The input...
```
var p = {
name: "<![CDATA[This is <b>HTML</b>]]>"
};
```

Will output...
```
<name>&lt;![CDATA[This is &lt;b&gt;HTML&lt;/b&gt;]]&gt;</name>
```

Any help would be appreciated!

Best,
Mel

**Comment by kawanet** [comment]
Hi @marlboro 

`toXML()` method accepts a special attribute `!` to output comments and CDATA sections.

```js
toXML({"xml": {"!": "-- comment here --"}})
=> '<xml><!-- comment here --></xml>'

toXML({"xml": {"!": "[CDATA[ cdata here ]]"}})
=> '<xml><![CDATA[ cdata here ]]></xml>'
```

Note that you need to wrap with `--` for comments and with `[CDATA[`...`]]` for CDATA sections.

**Comment by marlboro** [comment]
That worked great. Thank you!
