### ISSUE TITLE
HTML entities replace trailing and/or leading whitespace

### ISSUE THREAD

**Issue by arienshibani** [kawanet/to-xml#8]
The following JSON input

```json
{
  "firstName": "dave "
}
```

Gives me this XML

```xml
<firstName>Dave&#x20;</firstName>
```

Why does this only happen to leading / trailing whitespace, and more importantly, is there a way for this package to just ignore this and let it be? Thanks in advance.

**Comment by kawanet** [comment]
@arienshibani 
Hi! `&#x20;` is a hack to make it explicit that there is a leading and/or trailing whitespace in the string.
It allows rount trip conversions between the pair of [from-xml](https://github.com/kawanet/from-xml/) and `to-xml` modules.

XML#1

```xml
<parent>
    Foo
</parent>
```

The XML#1 above could be ambiguous for some cases. 
The trailing / leading spaces, including CR/LF, are ignored at the case.
The above should be parsed as below JSON#2 then.

JSON#2

```json
{
    "parent": "Foo"
}
```

However, there are some use cases to add explicit spaces at the first / end of the string. 
The hack could work for the case.

JSON#3

```json
{
    "parent": "\nFoo\n"
}
```


The JSON#3 above is encoded to XML#4 as below:

XML#4

```xml
<parent>&#x0a;Foo&#x0a;</parent>
```

The XML#4 could be parsed as JSON#3. The round-trip was done then.

By the way, the library has a replacer function feature but it unfortunately seems not to work for the case where a child object is not given.

```
toXML(value, replacer)
```

**Comment by arienshibani** [comment]
For my use case I'll simply use regex to remove these then. Thank you for your explanation @kawanet 🙏🏼
